font:
  size: 9
  normal: 
    family: "Fira Mono"

schemes:
  themer-dark: &dark
    primary:
      background: '#292c3e'
      foreground: '#cfd0d2'

    cursor:
      text: '#292c3e'
      cursor: '#a0e521'

    selection:
      text: '#292c3e'
      background: '#1ba6fa'

    normal:
      black: '#60636f'
      red: '#ff301b'
      green: '#a0e521'
      yellow: '#ffc620'
      blue: '#1ba6fa'
      magenta: '#b100b1'
      cyan: '#21deef'
      white: '#cfd0d2'

    bright:
      black: '#7c7e88'
      red: '#FB5545'
      green: '#AFE649'
      yellow: '#FBCD49'
      blue: '#45B4F7'
      magenta: '#BD2FBD'
      cyan: '#49E1EE'
      white: '#ebebeb'

    dim:
      black: '#454757'
      red: '#D42F22'
      green: '#88C027'
      yellow: '#D4A726'
      blue: '#1E8ED4'
      magenta: '#96099A'
      cyan: '#23BACC'
      white: '#b4b4ba'
  

  themer-light: &light
    primary:
      background: '#fffcff'
      foreground: '#474247'

    cursor:
      text: '#fffcff'
      cursor: '#bf65f0'

    selection:
      text: '#fffcff'
      background: '#53a6e1'

    normal:
      black: '#474247'
      red: '#f03e4d'
      green: '#97bd2d'
      yellow: '#eeba21'
      blue: '#53a6e1'
      magenta: '#ee4eb8'
      cyan: '#1fc598'
      white: '#c1bcc2'

    bright:
      black: '#656066'
      red: '#F36471'
      green: '#ACCA57'
      yellow: '#F1C74D'
      blue: '#75B7E7'
      magenta: '#F171C6'
      cyan: '#4CD0AD'
      white: '#e0dce0'

    dim:
      black: '#282629'
      red: '#C83946'
      green: '#819F2C'
      yellow: '#C69C23'
      blue: '#4A8CBC'
      magenta: '#C6469B'
      cyan: '#21A582'
      white: '#a29da3'

colors: *dark